On branch main 	modified:   README.md 	renamed:    bckp.sh -> backpoi 	modified:   bckp_conf.txt 	new file:   setup.sh
Bigfixes and firs step for automatic instalation

diff --git a/backpoi b/backpoi
--- a/backpoi
+++ b/backpoi
@@ -1,7 +1,7 @@
 #!/bin/bash
 
 readonly config_file="$(dirname "$0")/bckp_conf.txt"
-readonly log_file="/var/log/backpoi/bckp_logfile.log"
+readonly log_file="/var/log/bckp_logfile.log"
 readonly self_path="$(dirname "$0")/$(basename "$0")"
 
 exec 3>&1                           # Redirect desired logs only to console 
@@ -49,7 +49,17 @@ handle_command() {
     esac
 }
 
+check_if_run_as_root() {
+    if [[ $EUID -ne 0 ]]; then
+        log_message "$ERROR" "This script must be run as root" 
+        exit 1
+    else
+        log_message "$INFO" "Root access granted" 
+    fi
+}
+
 main() {
+    #check_if_run_as_root
     handle_command "$@"
     progress=""
     log_message "$INFO" "Logs are accesible here: $log_file"
@@ -141,7 +151,9 @@ logs() {
 }
 check_conf_file() {
     touch "$config_file" || { log_message "$ERROR" "Config file not found, backup not created!"; exit 1; }
+    #chmod 666 "$config_file"
     touch "$log_file" || { log_message "$ERROR" "Could not create log file"; exit 1; }
+    #chmod 666 "$log_file"
     log_level=$(grep -oP 'log_level=\K.*' "$config_file") 
 }
 read_conf_file() {
